### ISSUE TITLE
승낙헬퍼 리스트 보기

### ISSUE THREAD

**Issue by YJ17** [willson-appjam/willson-server#24]
승낙 헬퍼 리스트 보기에서 GET할때 question_idx 넘겨줘야 하던데 
누구의 question_idx를 넘겨줘야 하나요? 그거는 어디에서 받는 question_idx 인거죠??

**Comment by SooKim1110** [comment]
유저가 고민 생성하는 api에서 response로 question_idx를 주는데 그걸 가지고 있다가
승낙 헬퍼 리스트 보기에서 이 question_idx를 넘겨주면 될것같아!
